### ISSUE TITLE
Problema con migration

### ISSUE THREAD

**Issue by albsierra** [Frankyx93/proyecto#1]
El problema fundamental con la creación de las tablas de la base de datos es que en el datasources.json habéis llamado [mySessionDS](https://github.com/Frankyx93/proyecto/blob/60a340ba8da705b5804d4b26b4ada25b73501f77/mySession/server/datasources.json#L6) al datasource, mientras que en el archivo migration.js lo habéis llamado intentáis referenciar al datasource [mysqlDS](https://github.com/Frankyx93/proyecto/blob/60a340ba8da705b5804d4b26b4ada25b73501f77/mySession/server/boot/migration.js#L5).

Por otro lado, tenéis archivos de configuración que no utilizáis, como datasources.local.js y config.local.js

**Comment by Frankyx93** [comment]
Fixed
