### ISSUE TITLE
Quitar la propiedad url del datasource

### ISSUE THREAD

**Issue by albsierra** [Frankyx93/proyecto#2]
https://github.com/Frankyx93/proyecto/blob/33d9db11bc37093ab20e7e6cee93e6ae9c9bc66e/mySession/server/datasources.json#L9

Para que os funcione correctamente el acceso a la base de datos, deberíais quitar la línea de url, ya que sobreescribe los valores de otras de las propiedades del datasource.

**Comment by Frankyx93** [comment]
Solucionado
